CREATE TABLE decks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name varchar(200) NOT NULL,
    format smallint NOT NULL,
    hero smallint NOT NULL,
    fabrary_link varchar(512)
);

CREATE INDEX decks_user_id_idx ON decks (user_id);
CREATE INDEX decks_format_idx ON decks (format);
CREATE INDEX decks_hero_idx ON decks (hero);

CREATE TABLE deck_cards (
    deck_id integer NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    card_id integer NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    mainboard boolean NOT NULL DEFAULT true,
    PRIMARY KEY (deck_id, card_id, mainboard)
);

CREATE INDEX deck_cards_card_id_idx ON deck_cards (card_id);
CREATE INDEX deck_cards_deck_id_mainboard_idx ON deck_cards (deck_id, mainboard);
