CREATE TABLE cards (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL REFERENCES sets (id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    card_identifier varchar(100),
    image_url varchar(1024),
    functional_text varchar(2048),
    rarity smallint,
    set_code varchar(3) NOT NULL,
    set_num smallint NOT NULL,
    type smallint NOT NULL,
    subtypes smallint[],
    classes smallint[],
    hybrid boolean NOT NULL DEFAULT false,
    talents smallint[],
    pitch smallint,
    cost smallint,
    power smallint,
    block smallint,
    hero smallint,
    life smallint,
    intellect smallint,
    keywords smallint[],
    formats smallint[],
    specializations smallint[],
    fusions smallint[]
);

CREATE INDEX cards_card_identifier_idx ON cards (card_identifier);
CREATE INDEX cards_set_id_idx ON cards (set_id);
CREATE INDEX cards_rarity_idx ON cards (rarity);
CREATE INDEX cards_type_idx ON cards (type);
CREATE INDEX cards_subtypes_gin ON cards USING GIN (subtypes);
CREATE INDEX cards_classes_gin ON cards USING GIN (classes);
CREATE INDEX cards_talents_gin ON cards USING GIN (talents);
CREATE INDEX cards_pitch_idx ON cards (pitch);
CREATE INDEX cards_cost_idx ON cards (cost);
CREATE INDEX cards_power_idx ON cards (power);
CREATE INDEX cards_block_idx ON cards (block);
CREATE INDEX cards_keywords_gin ON cards USING GIN (keywords);
