CREATE TABLE deck_source (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source varchar(100) NOT NULL UNIQUE
);

INSERT INTO deck_source (source) VALUES ('Member');

ALTER TABLE decks
    ADD COLUMN deck_source_id integer NOT NULL DEFAULT 1 REFERENCES deck_source (id);

ALTER TABLE decks ALTER COLUMN deck_source_id DROP DEFAULT;

CREATE INDEX decks_deck_source_id_idx ON decks (deck_source_id);
