CREATE TABLE card_printings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id integer NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    set_code varchar(3) NOT NULL,
    set_num smallint NOT NULL,
    rarity smallint,
    image_url varchar(1024)
);

CREATE INDEX card_printings_card_id_idx ON card_printings (card_id);
CREATE INDEX card_printings_rarity_idx ON card_printings (rarity);
CREATE INDEX card_printings_set_code_set_num_idx ON card_printings (set_code, set_num);

INSERT INTO card_printings (card_id, set_code, set_num, rarity, image_url)
SELECT id, set_code, set_num, rarity, image_url
FROM cards;

ALTER TABLE cards
    DROP COLUMN image_url,
    DROP COLUMN rarity,
    DROP COLUMN set_code,
    DROP COLUMN set_num;

DROP INDEX IF EXISTS cards_rarity_idx;
