CREATE TABLE meetings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_at timestamptz NOT NULL,
    summary text NOT NULL,
    video_url varchar(1024),
    created_by_user_id integer NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX meetings_meeting_at_idx ON meetings (meeting_at DESC, id DESC);
