CREATE TABLE heroes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    type smallint NOT NULL,
    young boolean NOT NULL DEFAULT false,
    classes smallint[],
    talents smallint[],
    card_id integer REFERENCES cards (id) ON DELETE SET NULL,
    card_image_url varchar(1024),
    art_image_url varchar(1024)
);

CREATE INDEX heroes_type_idx ON heroes (type);
CREATE INDEX heroes_card_id_idx ON heroes (card_id);
CREATE INDEX heroes_classes_gin ON heroes USING GIN (classes);
CREATE INDEX heroes_talents_gin ON heroes USING GIN (talents);
