CREATE TABLE play_testing_session_recordings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES play_testing_sessions (id) ON DELETE CASCADE,
    recording_id integer NOT NULL REFERENCES recordings (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT play_testing_session_recordings_unique UNIQUE (session_id, recording_id)
);

CREATE INDEX play_testing_session_recordings_session_idx
    ON play_testing_session_recordings (session_id, created_at DESC);

CREATE INDEX play_testing_session_recordings_recording_idx
    ON play_testing_session_recordings (recording_id);
