CREATE TABLE play_testing_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    format smallint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX play_testing_sessions_created_at_idx ON play_testing_sessions (created_at DESC);
CREATE INDEX play_testing_sessions_user_id_idx ON play_testing_sessions (user_id);

-- side: 0 = play test with, 1 = play test against
CREATE TABLE play_testing_session_heroes (
    session_id integer NOT NULL REFERENCES play_testing_sessions (id) ON DELETE CASCADE,
    hero_id integer NOT NULL REFERENCES heroes (id) ON DELETE CASCADE,
    side smallint NOT NULL,
    PRIMARY KEY (session_id, side, hero_id),
    CONSTRAINT play_testing_session_heroes_side_check CHECK (side IN (0, 1))
);

CREATE INDEX play_testing_session_heroes_hero_id_idx ON play_testing_session_heroes (hero_id);

CREATE TABLE play_testing_session_timeframes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES play_testing_sessions (id) ON DELETE CASCADE,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz,
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT play_testing_session_timeframes_range_check CHECK (
        ends_at IS NULL OR ends_at >= starts_at
    )
);

CREATE INDEX play_testing_session_timeframes_session_id_idx
    ON play_testing_session_timeframes (session_id, sort_order ASC, id ASC);
