-- Role codes (match Go iota / enums in application code): 0=standard, 1=moderator, 2=admin, …
CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(320) NOT NULL,
    username varchar(64),
    uid varchar(128),
    role integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    registered_at timestamptz,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_uid_key UNIQUE (uid),
    CONSTRAINT users_role_nonnegative CHECK (role >= 0)
);

CREATE INDEX users_email_idx ON users (email);
