CREATE TABLE recordings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    url varchar(2048) NOT NULL,
    label varchar(512),
    first_hero_id integer REFERENCES heroes (id) ON DELETE SET NULL,
    second_hero_id integer REFERENCES heroes (id) ON DELETE SET NULL,
    format smallint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX recordings_user_id_idx ON recordings (user_id);
CREATE INDEX recordings_format_idx ON recordings (format);
CREATE INDEX recordings_first_hero_id_idx ON recordings (first_hero_id);
CREATE INDEX recordings_second_hero_id_idx ON recordings (second_hero_id);
CREATE INDEX recordings_created_at_idx ON recordings (created_at DESC);

CREATE TABLE recording_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id integer NOT NULL REFERENCES recordings (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    comment text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX recording_comments_recording_id_idx ON recording_comments (recording_id);
CREATE INDEX recording_comments_user_id_idx ON recording_comments (user_id);
CREATE INDEX recording_comments_created_at_idx ON recording_comments (created_at DESC);
