CREATE TABLE release_team_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    format smallint NOT NULL,
    set_id integer REFERENCES sets (id) ON DELETE SET NULL,
    status smallint NOT NULL DEFAULT 0,
    created_by_user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    CONSTRAINT release_team_sessions_status_check CHECK (status IN (0, 1))
);

CREATE INDEX release_team_sessions_status_created_idx
    ON release_team_sessions (status ASC, created_at DESC);

CREATE TABLE release_team_session_heroes (
    session_id integer NOT NULL REFERENCES release_team_sessions (id) ON DELETE CASCADE,
    hero_id integer NOT NULL REFERENCES heroes (id) ON DELETE CASCADE,
    PRIMARY KEY (session_id, hero_id)
);

CREATE INDEX release_team_session_heroes_hero_id_idx ON release_team_session_heroes (hero_id);

CREATE TABLE release_team_members (
    session_id integer NOT NULL REFERENCES release_team_sessions (id) ON DELETE CASCADE,
    hero_id integer NOT NULL REFERENCES heroes (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_captain boolean NOT NULL DEFAULT false,
    joined_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, hero_id, user_id),
    CONSTRAINT release_team_members_hero_fk
        FOREIGN KEY (session_id, hero_id)
        REFERENCES release_team_session_heroes (session_id, hero_id)
        ON DELETE CASCADE
);

CREATE INDEX release_team_members_user_id_idx ON release_team_members (user_id);

CREATE TABLE release_team_notes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL,
    hero_id integer NOT NULL,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT release_team_notes_team_fk
        FOREIGN KEY (session_id, hero_id)
        REFERENCES release_team_session_heroes (session_id, hero_id)
        ON DELETE CASCADE
);

CREATE INDEX release_team_notes_team_idx ON release_team_notes (session_id, hero_id, updated_at DESC);

CREATE TABLE release_team_decks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL,
    hero_id integer NOT NULL,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id integer NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT release_team_decks_team_fk
        FOREIGN KEY (session_id, hero_id)
        REFERENCES release_team_session_heroes (session_id, hero_id)
        ON DELETE CASCADE,
    CONSTRAINT release_team_decks_unique UNIQUE (session_id, hero_id, deck_id)
);

CREATE INDEX release_team_decks_team_idx ON release_team_decks (session_id, hero_id, created_at DESC);

CREATE TABLE release_team_recordings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL,
    hero_id integer NOT NULL,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    recording_id integer NOT NULL REFERENCES recordings (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT release_team_recordings_team_fk
        FOREIGN KEY (session_id, hero_id)
        REFERENCES release_team_session_heroes (session_id, hero_id)
        ON DELETE CASCADE,
    CONSTRAINT release_team_recordings_unique UNIQUE (session_id, hero_id, recording_id)
);

CREATE INDEX release_team_recordings_team_idx
    ON release_team_recordings (session_id, hero_id, created_at DESC);
