-- Owner notes (draft/publish) and interest sign-ups for Looking for Games sessions.

CREATE TABLE play_testing_session_notes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES play_testing_sessions (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    body text NOT NULL DEFAULT '',
    draft_body text NOT NULL DEFAULT '',
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT play_testing_session_notes_session_user_uidx UNIQUE (session_id, user_id)
);

CREATE INDEX play_testing_session_notes_session_id_idx
    ON play_testing_session_notes (session_id, updated_at DESC);

CREATE TABLE play_testing_session_interests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES play_testing_sessions (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    note text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT play_testing_session_interests_session_user_uidx UNIQUE (session_id, user_id)
);

CREATE INDEX play_testing_session_interests_session_id_idx
    ON play_testing_session_interests (session_id, updated_at DESC);

CREATE TABLE play_testing_session_interest_heroes (
    interest_id integer NOT NULL REFERENCES play_testing_session_interests (id) ON DELETE CASCADE,
    hero_id integer NOT NULL REFERENCES heroes (id) ON DELETE CASCADE,
    PRIMARY KEY (interest_id, hero_id)
);

CREATE INDEX play_testing_session_interest_heroes_hero_id_idx
    ON play_testing_session_interest_heroes (hero_id);
