-- Seed missing FAB sets from fabrary/cards setIdentifierToSetMappings + fullSetIdentifiers.
-- Sources:
--   https://github.com/fabrary/cards/blob/main/packages/types/src/sets.ts
--   https://github.com/fabrary/cards/blob/main/packages/types/src/interfaces.ts (Release enum display names)

CREATE UNIQUE INDEX IF NOT EXISTS sets_code_unique ON sets (code);

INSERT INTO sets (name, code, image_url)
SELECT v.name, v.code, v.image_url
FROM (
    VALUES
    ('History Pack 1', '1hp', NULL),
    ('Armory Deck: Arakni', 'aac', NULL),
    ('Armory Deck: Azalea', 'aaz', NULL),
    ('Armory Deck: Gravy Bones', 'agb', NULL),
    ('Armory Deck Origins: Hala', 'aha', NULL),
    ('Armory Deck: Dash', 'aio', NULL),
    ('Armory Deck Origins: Jarl', 'ajv', NULL),
    ('Armory Deck: Kayo', 'ako', NULL),
    ('Armory Deck: Maxx', 'amx', NULL),
    ('Promos', 'anq', NULL),
    ('Armory Deck: Olympia', 'aol', NULL),
    ('Armory Deck Legends: Prism', 'apr', NULL),
    ('Armory Deck: Pleiades', 'aps', NULL),
    ('Arakni Blitz Deck', 'ara', NULL),
    ('Arcane Rising', 'arc', NULL),
    ('Arakni Hunted Blitz Deck', 'ark', NULL),
    ('Armory Deck: Rhinar', 'arr', NULL),
    ('Armory Deck: Boltyn', 'asb', NULL),
    ('Armory Deck: Ira', 'asr', NULL),
    ('Armory Deck: Aurora', 'ast', NULL),
    ('Aurora Blitz Deck', 'aua', NULL),
    ('1st Strike: Aurora', 'aur', NULL),
    ('Armory Deck Legends: Viserai', 'avs', NULL),
    ('Azalea Blitz Deck', 'azl', NULL),
    ('Armory Deck: Zyggy', 'azs', NULL),
    ('Bravo Demo Deck', 'bdd', NULL),
    ('Benji Blitz Deck', 'ben', NULL),
    ('Betsy Blitz Deck', 'bet', NULL),
    ('Boltyn Blitz Deck', 'bol', NULL),
    ('Briar Blitz Deck', 'bri', NULL),
    ('Bravo Hero Deck', 'bvo', NULL),
    ('Chane Blitz Deck', 'chn', NULL),
    ('Cindra Blitz Deck', 'cin', NULL),
    ('Promos', 'con', NULL),
    ('Crucible of War', 'cru', NULL),
    ('Dorinthea Demo Deck', 'ddd', NULL),
    ('Dromai Blitz Deck', 'dro', NULL),
    ('Dusk till Dawn', 'dtd', NULL),
    ('Classic Battles: Rhinar vs Dorinthea', 'dvr', NULL),
    ('Dynasty', 'dyn', NULL),
    ('Tales of Aria', 'ele', NULL),
    ('Enigma Blitz Deck', 'eng', NULL),
    ('Bright Lights', 'evo', NULL),
    ('Everfest', 'evr', NULL),
    ('Promos', 'fab', NULL),
    ('Fai Blitz Deck', 'fai', NULL),
    ('Florian Blitz Deck', 'flr', NULL),
    ('Fang Blitz Deck', 'fng', NULL),
    ('GEM', 'gem', NULL),
    ('Promos', 'her', NULL),
    ('The Hunted', 'hnt', NULL),
    ('History Pack 1', 'hp1', NULL),
    ('Heavy Hitters', 'hvy', NULL),
    ('IAR', 'iar', NULL),
    ('Ira Welcome Deck', 'ira', NULL),
    ('Promos', 'jdg', NULL),
    ('Katsu Blitz Deck', 'kat', NULL),
    ('Kassai Blitz Deck', 'ksi', NULL),
    ('Katsu Hero Deck', 'ksu', NULL),
    ('Kayo Blitz Deck', 'kyo', NULL),
    ('Levia Blitz Deck', 'lev', NULL),
    ('Promos', 'lgs', NULL),
    ('Promos', 'lss', NULL),
    ('Lexi Blitz Deck', 'lxi', NULL),
    ('Monarch', 'mon', NULL),
    ('Mastery Pack: Guardian', 'mpg', NULL),
    ('Mastery Pack: Warrior', 'mpw', NULL),
    ('Part the Mistveil', 'mst', NULL),
    ('Nuu Blitz Deck', 'nuu', NULL),
    ('Olympia Blitz Deck', 'ola', NULL),
    ('Oldhim Blitz Deck', 'old', NULL),
    ('Omens of the Third Age', 'omn', NULL),
    ('Oscilio Blitz Deck', 'osc', NULL),
    ('Outsiders', 'out', NULL),
    ('Promos', 'oxo', NULL),
    ('Compendium of Rathe', 'pen', NULL),
    ('Prism Blitz Deck', 'psm', NULL),
    ('Rhinar Blitz Deck', 'rhi', NULL),
    ('Riptide Blitz Deck', 'rip', NULL),
    ('Rhinar Hero Deck', 'rnr', NULL),
    ('Rosetta', 'ros', NULL),
    ('Classic Battles: Rhinar vs Dorinthea', 'rvd', NULL),
    ('Arakni Silver Age Deck', 'sar', NULL),
    ('Azalea Silver Age Deck', 'saz', NULL),
    ('Briar Silver Age Deck', 'sba', NULL),
    ('Boltyn Silver Age Deck', 'sbl', NULL),
    ('Bravo Silver Age Deck', 'sbr', NULL),
    ('Blaze Silver Age Deck', 'sbz', NULL),
    ('Dash Silver Age Deck', 'sda', NULL),
    ('Dorinthea Silver Age Deck', 'sdo', NULL),
    ('High Seas', 'sea', NULL),
    ('Enigma Silver Age Deck', 'sen', NULL),
    ('Fai Silver Age Deck', 'sfa', NULL),
    ('Gravy Bones Silver Age Deck', 'sgb', NULL),
    ('Iyslander Silver Age Deck', 'siy', NULL),
    ('Kayo Silver Age Deck', 'ska', NULL),
    ('Lyath Silver Age Deck', 'sly', NULL),
    ('Smash Palace', 'smp', NULL),
    ('Super Slam', 'sup', NULL),
    ('Viserai Silver Age Deck', 'svi', NULL),
    ('Round the Table: TCC x LSS', 'tcc', NULL),
    ('Dorinthea Hero Deck', 'tea', NULL),
    ('1st Strike: Terra', 'ter', NULL),
    ('Tournament Pack', 'tnp', NULL),
    ('Uprising', 'upr', NULL),
    ('Uzuri Blitz Deck', 'uzu', NULL),
    ('Verdance Blitz Deck', 'ver', NULL),
    ('Victor Blitz Deck', 'vic', NULL),
    ('Promos', 'win', NULL),
    ('Arakni, Web of Deceit Blitz Deck', 'wod', NULL),
    ('Welcome to Rathe', 'wtr', NULL),
    ('Promos', 'xxx', NULL),
    ('Zen Blitz Deck', 'zen', NULL)
) AS v(name, code, image_url)
WHERE NOT EXISTS (
    SELECT 1 FROM sets s WHERE s.code = v.code
);

