/**
 * Card keyword enum IDs (smallint in `keywords` arrays). Must match `backend/internal/domain/card_keyword.go`.
 * @readonly
 */
export const CardKeyword = Object.freeze({
  Ambush: 0,
  Amp: 1,
  ArcaneBarrier: 2,
  ArcaneShelter: 3,
  Awaken: 4,
  Battleworn: 5,
  BeatChest: 6,
  BladeBreak: 7,
  BloodDebt: 8,
  Boost: 9,
  Bond: 10,
  Channel: 11,
  Charge: 12,
  Clash: 13,
  Cloaked: 14,
  Combo: 15,
  Contract: 16,
  Crank: 17,
  TheCrowdBoos: 18,
  TheCrowdCheers: 19,
  Crush: 20,
  Decompose: 21,
  Dominate: 22,
  Ephemeral: 23,
  Essence: 24,
  EvoUpgrade: 25,
  Flow: 26,
  Freeze: 27,
  Fusion: 28,
  Galvanize: 29,
  GoAgain: 30,
  GoFish: 31,
  Guardwell: 32,
  Heave: 33,
  Heavy: 34,
  HighTide: 35,
  Intimidate: 36,
  Legendary: 37,
  Mark: 38,
  Material: 39,
  Meld: 40,
  Modular: 41,
  Mirage: 42,
  Negate: 43,
  Opt: 44,
  Overpower: 45,
  Pairs: 46,
  Piercing: 47,
  Phantasm: 48,
  Protect: 49,
  Quell: 50,
  Quickstrike: 51,
  Reload: 52,
  Reprise: 53,
  Retrieve: 54,
  RuneGate: 55,
  Rupture: 56,
  Scrap: 57,
  Sharpen: 58,
  Solflare: 59,
  Specialization: 60,
  Spectra: 61,
  Spellvoid: 62,
  Starfall: 63,
  Steal: 64,
  Stealth: 65,
  Surge: 66,
  Suspense: 67,
  Temper: 68,
  Tower: 69,
  Transform: 70,
  Transcend: 71,
  Unlimited: 72,
  Universal: 73,
  Unfreeze: 74,
  Unity: 75,
  Wager: 76,
  Ward: 77,
  WateryGrave: 78,
});

/** Ordered display names for each ID 0..78. */
export const CARD_KEYWORD_NAMES = Object.freeze([
  "Ambush",
  "Amp",
  "Arcane Barrier",
  "Arcane Shelter",
  "Awaken",
  "Battleworn",
  "Beat Chest",
  "Blade Break",
  "Blood Debt",
  "Boost",
  "Bond",
  "Channel",
  "Charge",
  "Clash",
  "Cloaked",
  "Combo",
  "Contract",
  "Crank",
  "The Crowd Boos",
  "The Crowd Cheers",
  "Crush",
  "Decompose",
  "Dominate",
  "Ephemeral",
  "Essence",
  "Evo Upgrade",
  "Flow",
  "Freeze",
  "Fusion",
  "Galvanize",
  "Go again",
  "Go Fish",
  "Guardwell",
  "Heave",
  "Heavy",
  "High Tide",
  "Intimidate",
  "Legendary",
  "Mark",
  "Material",
  "Meld",
  "Modular",
  "Mirage",
  "Negate",
  "Opt",
  "Overpower",
  "Pairs",
  "Piercing",
  "Phantasm",
  "Protect",
  "Quell",
  "Quickstrike",
  "Reload",
  "Reprise",
  "Retrieve",
  "Rune Gate",
  "Rupture",
  "Scrap",
  "Sharpen",
  "Solflare",
  "Specialization",
  "Spectra",
  "Spellvoid",
  "Starfall",
  "Steal",
  "Stealth",
  "Surge",
  "Suspense",
  "Temper",
  "Tower",
  "Transform",
  "Transcend",
  "Unlimited",
  "Universal",
  "Unfreeze",
  "Unity",
  "Wager",
  "Ward",
  "Watery Grave",
]);

/**
 * @param {number} id
 * @returns {string | undefined}
 */
export function cardKeywordName(id) {
  return CARD_KEYWORD_NAMES[id];
}

/**
 * @param {number} id
 * @returns {boolean}
 */
export function isValidCardKeywordId(id) {
  return Number.isInteger(id) && id >= 0 && id < CARD_KEYWORD_NAMES.length;
}
