package repository

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// ErrCardNotFound is returned when no row matches the requested card identifier.
var ErrCardNotFound = errors.New("repository: card not found")

// Card is a row from cards.
type Card struct {
	ID             int
	SetID          int
	Name           string
	ImageURL       *string
	FunctionalText *string
	Rarity         *int16
	SetCode        string
	SetNum         int16
	Type           int16
	Subtypes       []int16
	Classes        []int16
	Hybrid         bool
	Talents        []int16
	Pitch          *int16
	Cost           *int16
	Power          *int16
	Block          *int16
	Hero           *int16
	Life           *int16
	Intellect      *int16
	Keywords       []int16
	Formats        []int16
}

// CreateCardInput holds fields to insert a card (id is generated by the DB).
// Nil slices and pointers persist as NULL where the column is nullable.
type CreateCardInput struct {
	SetID          int
	Name           string
	ImageURL       *string
	FunctionalText *string
	Rarity         *int16
	SetCode        string
	SetNum         int16
	Type           int16
	Subtypes       []int16
	Classes        []int16
	Hybrid         bool
	Talents        []int16
	Pitch          *int16
	Cost           *int16
	Power          *int16
	Block          *int16
	Hero           *int16
	Life           *int16
	Intellect      *int16
	Keywords       []int16
	Formats        []int16
}

func scanCard(row pgx.Row) (*Card, error) {
	var c Card
	err := row.Scan(
		&c.ID,
		&c.SetID,
		&c.Name,
		&c.ImageURL,
		&c.FunctionalText,
		&c.Rarity,
		&c.SetCode,
		&c.SetNum,
		&c.Type,
		&c.Subtypes,
		&c.Classes,
		&c.Hybrid,
		&c.Talents,
		&c.Pitch,
		&c.Cost,
		&c.Power,
		&c.Block,
		&c.Hero,
		&c.Life,
		&c.Intellect,
		&c.Keywords,
		&c.Formats,
	)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

const cardSelectColumns = `
id, set_id, name, image_url, functional_text, rarity, set_code, set_num, type,
subtypes, classes, hybrid, talents, pitch, cost, power, block, hero, life, intellect,
keywords, formats`

// CreateCard inserts a card and returns the persisted row.
func (r *Repository) CreateCard(ctx context.Context, in CreateCardInput) (*Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
INSERT INTO cards (
	set_id, name, image_url, functional_text, rarity, set_code, set_num, type,
	subtypes, classes, hybrid, talents, pitch, cost, power, block, hero, life, intellect,
	keywords, formats
)
VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8,
	$9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
	$20, $21
)
RETURNING ` + cardSelectColumns
	row := r.pool.QueryRow(ctx, q,
		in.SetID,
		in.Name,
		in.ImageURL,
		in.FunctionalText,
		in.Rarity,
		in.SetCode,
		in.SetNum,
		in.Type,
		in.Subtypes,
		in.Classes,
		in.Hybrid,
		in.Talents,
		in.Pitch,
		in.Cost,
		in.Power,
		in.Block,
		in.Hero,
		in.Life,
		in.Intellect,
		in.Keywords,
		in.Formats,
	)
	c, err := scanCard(row)
	if err != nil {
		return nil, fmt.Errorf("repository: create card: %w", err)
	}
	return c, nil
}

// CardByID returns the card with the given id, or ErrCardNotFound.
func (r *Repository) CardByID(ctx context.Context, id int) (*Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `SELECT ` + cardSelectColumns + ` FROM cards WHERE id = $1`
	row := r.pool.QueryRow(ctx, q, id)
	c, err := scanCard(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrCardNotFound
		}
		return nil, fmt.Errorf("repository: card by id: %w", err)
	}
	return c, nil
}

// CardsBySetID returns all cards for a set, ordered by set_num then id.
func (r *Repository) CardsBySetID(ctx context.Context, setID int) ([]Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `SELECT ` + cardSelectColumns + ` FROM cards WHERE set_id = $1 ORDER BY set_num ASC, id ASC`
	rows, err := r.pool.Query(ctx, q, setID)
	if err != nil {
		return nil, fmt.Errorf("repository: cards by set id: %w", err)
	}
	defer rows.Close()

	out := make([]Card, 0, 64)
	for rows.Next() {
		var c Card
		err := rows.Scan(
			&c.ID,
			&c.SetID,
			&c.Name,
			&c.ImageURL,
			&c.FunctionalText,
			&c.Rarity,
			&c.SetCode,
			&c.SetNum,
			&c.Type,
			&c.Subtypes,
			&c.Classes,
			&c.Hybrid,
			&c.Talents,
			&c.Pitch,
			&c.Cost,
			&c.Power,
			&c.Block,
			&c.Hero,
			&c.Life,
			&c.Intellect,
			&c.Keywords,
			&c.Formats,
		)
		if err != nil {
			return nil, fmt.Errorf("repository: cards by set id scan: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: cards by set id rows: %w", err)
	}
	return out, nil
}
