package repository

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// ErrCardNotFound is returned when no row matches the requested card identifier.
var ErrCardNotFound = errors.New("repository: card not found")

// Card is a row from cards.
type Card struct {
	ID              int
	SetID           int
	Name            string
	CardIdentifier  *string
	ImageURL        *string
	FunctionalText  *string
	Rarity          *int16
	SetCode         string
	SetNum          int16
	Type            int16
	Subtypes        []int16
	Classes         []int16
	Hybrid          bool
	Talents         []int16
	Pitch           *int16
	Cost            *int16
	Power           *int16
	Block           *int16
	Heroes          []int16
	Life            *int16
	Intellect       *int16
	Keywords        []int16
	Formats         []int16
	Specializations []int16
	Fusions         []int16
	// SetName is set when listing with a join to sets (ListCards); otherwise empty.
	SetName string
}

// CreateCardInput holds fields to insert a card (id is generated by the DB).
// Nil slices and pointers persist as NULL where the column is nullable.
type CreateCardInput struct {
	SetID           int
	Name            string
	CardIdentifier  *string
	ImageURL        *string
	FunctionalText  *string
	Rarity          *int16
	SetCode         string
	SetNum          int16
	Type            int16
	Subtypes        []int16
	Classes         []int16
	Hybrid          bool
	Talents         []int16
	Pitch           *int16
	Cost            *int16
	Power           *int16
	Block           *int16
	Heroes          []int16
	Life            *int16
	Intellect       *int16
	Keywords        []int16
	Formats         []int16
	Specializations []int16
	Fusions         []int16
}

func scanCard(row pgx.Row) (*Card, error) {
	var c Card
	err := row.Scan(
		&c.ID,
		&c.SetID,
		&c.Name,
		&c.CardIdentifier,
		&c.ImageURL,
		&c.FunctionalText,
		&c.Rarity,
		&c.SetCode,
		&c.SetNum,
		&c.Type,
		&c.Subtypes,
		&c.Classes,
		&c.Hybrid,
		&c.Talents,
		&c.Pitch,
		&c.Cost,
		&c.Power,
		&c.Block,
		&c.Heroes,
		&c.Life,
		&c.Intellect,
		&c.Keywords,
		&c.Formats,
		&c.Specializations,
		&c.Fusions,
	)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

const cardSelectColumns = `
id, set_id, name, card_identifier, image_url, functional_text, rarity, set_code, set_num, type,
subtypes, classes, hybrid, talents, pitch, cost, power, block, heroes, life, intellect,
keywords, formats, specializations, fusions`

// Qualified columns for JOIN queries (cards aliased as c).
const cardSelectColumnsFromC = `
c.id, c.set_id, c.name, c.card_identifier, c.image_url, c.functional_text, c.rarity, c.set_code, c.set_num, c.type,
c.subtypes, c.classes, c.hybrid, c.talents, c.pitch, c.cost, c.power, c.block, c.heroes, c.life, c.intellect,
c.keywords, c.formats, c.specializations, c.fusions`

type cardQuerier interface {
	QueryRow(context.Context, string, ...any) pgx.Row
}

const insertCardQuery = `
INSERT INTO cards (
	set_id, name, card_identifier, image_url, functional_text, rarity, set_code, set_num, type,
	subtypes, classes, hybrid, talents, pitch, cost, power, block, heroes, life, intellect,
	keywords, formats, specializations, fusions
)
VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9,
	$10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
	$21, $22, $23, $24
)
RETURNING ` + cardSelectColumns

func insertCardReturning(ctx context.Context, q cardQuerier, in CreateCardInput) (*Card, error) {
	row := q.QueryRow(ctx, insertCardQuery,
		in.SetID,
		in.Name,
		in.CardIdentifier,
		in.ImageURL,
		in.FunctionalText,
		in.Rarity,
		in.SetCode,
		in.SetNum,
		in.Type,
		in.Subtypes,
		in.Classes,
		in.Hybrid,
		in.Talents,
		in.Pitch,
		in.Cost,
		in.Power,
		in.Block,
		in.Heroes,
		in.Life,
		in.Intellect,
		in.Keywords,
		in.Formats,
		in.Specializations,
		in.Fusions,
	)
	return scanCard(row)
}

// CreateCard inserts a card and returns the persisted row.
func (r *Repository) CreateCard(ctx context.Context, in CreateCardInput) (*Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	c, err := insertCardReturning(ctx, r.pool, in)
	if err != nil {
		return nil, fmt.Errorf("repository: create card: %w", err)
	}
	return c, nil
}

// CreateCardsBatch inserts cards in one transaction (all-or-nothing).
func (r *Repository) CreateCardsBatch(ctx context.Context, inputs []CreateCardInput) ([]Card, error) {
	if len(inputs) == 0 {
		return nil, nil
	}
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("repository: batch begin: %w", err)
	}
	defer tx.Rollback(ctx)

	out := make([]Card, 0, len(inputs))
	for i := range inputs {
		c, err := insertCardReturning(ctx, tx, inputs[i])
		if err != nil {
			return nil, fmt.Errorf("repository: batch item %d: %w", i, err)
		}
		out = append(out, *c)
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("repository: batch commit: %w", err)
	}
	return out, nil
}

// CardByID returns the card with the given id, or ErrCardNotFound.
func (r *Repository) CardByID(ctx context.Context, id int) (*Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `SELECT ` + cardSelectColumns + ` FROM cards WHERE id = $1`
	row := r.pool.QueryRow(ctx, q, id)
	c, err := scanCard(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrCardNotFound
		}
		return nil, fmt.Errorf("repository: card by id: %w", err)
	}
	return c, nil
}

// CardsBySetID returns all cards for a set, ordered by set_num then id.
func (r *Repository) CardsBySetID(ctx context.Context, setID int) ([]Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `SELECT ` + cardSelectColumns + ` FROM cards WHERE set_id = $1 ORDER BY set_num ASC, id ASC`
	rows, err := r.pool.Query(ctx, q, setID)
	if err != nil {
		return nil, fmt.Errorf("repository: cards by set id: %w", err)
	}
	defer rows.Close()

	out := make([]Card, 0, 64)
	for rows.Next() {
		var c Card
		err := rows.Scan(
			&c.ID,
			&c.SetID,
			&c.Name,
			&c.CardIdentifier,
			&c.ImageURL,
			&c.FunctionalText,
			&c.Rarity,
			&c.SetCode,
			&c.SetNum,
			&c.Type,
			&c.Subtypes,
			&c.Classes,
			&c.Hybrid,
			&c.Talents,
			&c.Pitch,
			&c.Cost,
			&c.Power,
			&c.Block,
			&c.Heroes,
			&c.Life,
			&c.Intellect,
			&c.Keywords,
			&c.Formats,
			&c.Specializations,
			&c.Fusions,
		)
		if err != nil {
			return nil, fmt.Errorf("repository: cards by set id scan: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: cards by set id rows: %w", err)
	}
	return out, nil
}

// ListCards returns every card with set display name, ordered by set_code, set_num, id.
func (r *Repository) ListCards(ctx context.Context) ([]Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `
SELECT ` + cardSelectColumnsFromC + `, s.name AS set_name
FROM cards c
INNER JOIN sets s ON s.id = c.set_id
ORDER BY c.set_code ASC, c.set_num ASC, c.id ASC`
	rows, err := r.pool.Query(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("repository: list cards: %w", err)
	}
	defer rows.Close()

	out := make([]Card, 0, 256)
	for rows.Next() {
		var c Card
		err := rows.Scan(
			&c.ID,
			&c.SetID,
			&c.Name,
			&c.CardIdentifier,
			&c.ImageURL,
			&c.FunctionalText,
			&c.Rarity,
			&c.SetCode,
			&c.SetNum,
			&c.Type,
			&c.Subtypes,
			&c.Classes,
			&c.Hybrid,
			&c.Talents,
			&c.Pitch,
			&c.Cost,
			&c.Power,
			&c.Block,
			&c.Heroes,
			&c.Life,
			&c.Intellect,
			&c.Keywords,
			&c.Formats,
			&c.Specializations,
			&c.Fusions,
			&c.SetName,
		)
		if err != nil {
			return nil, fmt.Errorf("repository: list cards scan: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: list cards rows: %w", err)
	}
	return out, nil
}
