package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

// ErrCardNotFound is returned when no row matches the requested card identifier.
var ErrCardNotFound = errors.New("repository: card not found")

// Card is a row from cards joined to its primary printing (lowest card_printings.id).
type Card struct {
	ID              int
	SetID           int
	Name            string
	CardIdentifier  *string
	ImageURL        *string
	FunctionalText  *string
	Rarity          *int16
	SetCode         string
	SetNum          int16
	Type            int16
	Subtypes        []int16
	Classes         []int16
	Hybrid          bool
	Talents         []int16
	Pitch           *int16
	Cost            *int16
	Power           *int16
	Block           *int16
	Heroes          []int16
	Life            *int16
	Intellect       *int16
	Keywords        []int16
	Formats         []int16
	Specializations []int16
	Fusions         []int16
	// SetName is set when listing with a join to sets (ListCards); otherwise empty.
	SetName string
	// Printings is populated when AttachPrintings is called before API serialization.
	Printings []CardPrinting
}

// CreateCardPrintingInput holds one row for card_printings on insert.
type CreateCardPrintingInput struct {
	SetCode  string
	SetNum   int16
	Rarity   *int16
	ImageURL *string
}

// CreateCardInput holds fields to insert a card and its printings (card id is generated by the DB).
// Nil slices and pointers persist as NULL where the column is nullable.
type CreateCardInput struct {
	SetID           int
	Name            string
	CardIdentifier  *string
	ImageURL        *string
	FunctionalText  *string
	Rarity          *int16
	SetCode         string
	SetNum          int16
	Type            int16
	Subtypes        []int16
	Classes         []int16
	Hybrid          bool
	Talents         []int16
	Pitch           *int16
	Cost            *int16
	Power           *int16
	Block           *int16
	Heroes          []int16
	Life            *int16
	Intellect       *int16
	Keywords        []int16
	Formats         []int16
	Specializations []int16
	Fusions         []int16
	Printings       []CreateCardPrintingInput
}

// Primary printing = lowest card_printings.id per card (matches migrated 1:1 rows).
const cardPrintingLateralJoin = `
INNER JOIN LATERAL (
	SELECT cp.image_url, cp.rarity, cp.set_code, cp.set_num
	FROM card_printings cp
	WHERE cp.card_id = c.id
	ORDER BY cp.id ASC
	LIMIT 1
) cp ON true`

const cardSelectColumns = `
c.id, c.set_id, c.name, c.card_identifier, cp.image_url, c.functional_text, cp.rarity, cp.set_code, cp.set_num, c.type,
c.subtypes, c.classes, c.hybrid, c.talents, c.pitch, c.cost, c.power, c.block, c.heroes, c.life, c.intellect,
c.keywords, c.formats, c.specializations, c.fusions`

// Qualified columns for JOIN queries (cards aliased as c).
const cardSelectColumnsFromC = cardSelectColumns

// Used when GROUP BY c.id also selects primary printing columns.
const cardPrintingGroupBy = `c.id, cp.image_url, cp.rarity, cp.set_code, cp.set_num`

func scanCard(row pgx.Row) (*Card, error) {
	var c Card
	err := row.Scan(
		&c.ID,
		&c.SetID,
		&c.Name,
		&c.CardIdentifier,
		&c.ImageURL,
		&c.FunctionalText,
		&c.Rarity,
		&c.SetCode,
		&c.SetNum,
		&c.Type,
		&c.Subtypes,
		&c.Classes,
		&c.Hybrid,
		&c.Talents,
		&c.Pitch,
		&c.Cost,
		&c.Power,
		&c.Block,
		&c.Heroes,
		&c.Life,
		&c.Intellect,
		&c.Keywords,
		&c.Formats,
		&c.Specializations,
		&c.Fusions,
	)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

type cardQuerier interface {
	QueryRow(context.Context, string, ...any) pgx.Row
}

const insertCardQuery = `
INSERT INTO cards (
	set_id, name, card_identifier, functional_text, type,
	subtypes, classes, hybrid, talents, pitch, cost, power, block, heroes, life, intellect,
	keywords, formats, specializations, fusions
)
VALUES (
	$1, $2, $3, $4, $5,
	$6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
	$17, $18, $19, $20
)
RETURNING id, set_id, name, card_identifier, functional_text, type,
subtypes, classes, hybrid, talents, pitch, cost, power, block, heroes, life, intellect,
keywords, formats, specializations, fusions`

const insertCardPrintingQuery = `
INSERT INTO card_printings (card_id, set_code, set_num, rarity, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id`

func insertCardReturning(ctx context.Context, q cardQuerier, in CreateCardInput) (*Card, error) {
	row := q.QueryRow(ctx, insertCardQuery,
		in.SetID,
		in.Name,
		in.CardIdentifier,
		in.FunctionalText,
		in.Type,
		in.Subtypes,
		in.Classes,
		in.Hybrid,
		in.Talents,
		in.Pitch,
		in.Cost,
		in.Power,
		in.Block,
		in.Heroes,
		in.Life,
		in.Intellect,
		in.Keywords,
		in.Formats,
		in.Specializations,
		in.Fusions,
	)
	var c Card
	err := row.Scan(
		&c.ID,
		&c.SetID,
		&c.Name,
		&c.CardIdentifier,
		&c.FunctionalText,
		&c.Type,
		&c.Subtypes,
		&c.Classes,
		&c.Hybrid,
		&c.Talents,
		&c.Pitch,
		&c.Cost,
		&c.Power,
		&c.Block,
		&c.Heroes,
		&c.Life,
		&c.Intellect,
		&c.Keywords,
		&c.Formats,
		&c.Specializations,
		&c.Fusions,
	)
	if err != nil {
		return nil, err
	}
	printings := in.Printings
	if len(printings) == 0 {
		printings = []CreateCardPrintingInput{{
			SetCode:  in.SetCode,
			SetNum:   in.SetNum,
			Rarity:   in.Rarity,
			ImageURL: in.ImageURL,
		}}
	}
	c.Printings = make([]CardPrinting, 0, len(printings))
	for _, p := range printings {
		var printingID int
		if err := q.QueryRow(ctx, insertCardPrintingQuery,
			c.ID,
			p.SetCode,
			p.SetNum,
			p.Rarity,
			p.ImageURL,
		).Scan(&printingID); err != nil {
			return nil, err
		}
		c.Printings = append(c.Printings, CardPrinting{
			ID:       printingID,
			CardID:   c.ID,
			SetCode:  p.SetCode,
			SetNum:   p.SetNum,
			Rarity:   p.Rarity,
			ImageURL: p.ImageURL,
		})
	}
	if len(c.Printings) > 0 {
		p0 := c.Printings[0]
		c.ImageURL = p0.ImageURL
		c.Rarity = p0.Rarity
		c.SetCode = p0.SetCode
		c.SetNum = p0.SetNum
	}
	return &c, nil
}

// ListAllCardIdentifiersLower returns lower(trim(card_identifier)) for every card with an identifier.
func (r *Repository) ListAllCardIdentifiersLower(ctx context.Context) (map[string]struct{}, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
SELECT lower(trim(card_identifier))
FROM cards
WHERE card_identifier IS NOT NULL AND trim(card_identifier) <> ''`
	rows, err := r.pool.Query(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("repository: list all card identifiers: %w", err)
	}
	defer rows.Close()
	out := make(map[string]struct{})
	for rows.Next() {
		var ident string
		if err := rows.Scan(&ident); err != nil {
			return nil, fmt.Errorf("repository: list all card identifiers scan: %w", err)
		}
		if ident != "" {
			out[ident] = struct{}{}
		}
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: list all card identifiers rows: %w", err)
	}
	return out, nil
}

// ListCardIdentifiersLowerBySetID returns lower(trim(card_identifier)) for all non-null identifiers in a set.
func (r *Repository) ListCardIdentifiersLowerBySetID(ctx context.Context, setID int) (map[string]struct{}, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
SELECT lower(trim(card_identifier))
FROM cards
WHERE set_id = $1 AND card_identifier IS NOT NULL AND trim(card_identifier) <> ''`
	rows, err := r.pool.Query(ctx, q, setID)
	if err != nil {
		return nil, fmt.Errorf("repository: list card identifiers by set: %w", err)
	}
	defer rows.Close()
	out := make(map[string]struct{})
	for rows.Next() {
		var ident string
		if err := rows.Scan(&ident); err != nil {
			return nil, fmt.Errorf("repository: list card identifiers scan: %w", err)
		}
		if ident != "" {
			out[ident] = struct{}{}
		}
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: list card identifiers rows: %w", err)
	}
	return out, nil
}

// CreateCard inserts a card and returns the persisted row.
func (r *Repository) CreateCard(ctx context.Context, in CreateCardInput) (*Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	c, err := insertCardReturning(ctx, r.pool, in)
	if err != nil {
		return nil, fmt.Errorf("repository: create card: %w", err)
	}
	return c, nil
}

// CreateCardsBatch inserts cards in one transaction (all-or-nothing).
func (r *Repository) CreateCardsBatch(ctx context.Context, inputs []CreateCardInput) ([]Card, error) {
	if len(inputs) == 0 {
		return nil, nil
	}
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("repository: batch begin: %w", err)
	}
	defer tx.Rollback(ctx)

	out := make([]Card, 0, len(inputs))
	for i := range inputs {
		c, err := insertCardReturning(ctx, tx, inputs[i])
		if err != nil {
			return nil, fmt.Errorf("repository: batch item %d: %w", i, err)
		}
		out = append(out, *c)
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("repository: batch commit: %w", err)
	}
	return out, nil
}

// cardSelectJoinSet is cards plus set display name (set_name), for single-card reads and lists.
const cardSelectJoinSet = `
SELECT ` + cardSelectColumnsFromC + `, s.name AS set_name
FROM cards c
` + cardPrintingLateralJoin + `
INNER JOIN sets s ON s.id = c.set_id
`

// CardByID returns the card with the given id, or ErrCardNotFound.
func (r *Repository) CardByID(ctx context.Context, id int) (*Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := cardSelectJoinSet + ` WHERE c.id = $1`
	row := r.pool.QueryRow(ctx, q, id)
	c, err := scanCardWithSetName(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrCardNotFound
		}
		return nil, fmt.Errorf("repository: card by id: %w", err)
	}
	return c, nil
}

func scanCardWithSetName(row pgx.Row) (*Card, error) {
	var c Card
	err := row.Scan(
		&c.ID,
		&c.SetID,
		&c.Name,
		&c.CardIdentifier,
		&c.ImageURL,
		&c.FunctionalText,
		&c.Rarity,
		&c.SetCode,
		&c.SetNum,
		&c.Type,
		&c.Subtypes,
		&c.Classes,
		&c.Hybrid,
		&c.Talents,
		&c.Pitch,
		&c.Cost,
		&c.Power,
		&c.Block,
		&c.Heroes,
		&c.Life,
		&c.Intellect,
		&c.Keywords,
		&c.Formats,
		&c.Specializations,
		&c.Fusions,
		&c.SetName,
	)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

// CardByCardIdentifier returns the card with the given card_identifier, or ErrCardNotFound.
func (r *Repository) CardByCardIdentifier(ctx context.Context, identifier string) (*Card, error) {
	ident := strings.TrimSpace(identifier)
	if ident == "" {
		return nil, ErrCardNotFound
	}
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := cardSelectJoinSet + ` WHERE c.card_identifier = $1`
	row := r.pool.QueryRow(ctx, q, ident)
	c, err := scanCardWithSetName(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrCardNotFound
		}
		return nil, fmt.Errorf("repository: card by card_identifier: %w", err)
	}
	return c, nil
}

// CardsBySetID returns all cards for a set, ordered by set_num then id.
func (r *Repository) CardsBySetID(ctx context.Context, setID int) ([]Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `
SELECT ` + cardSelectColumns + `
FROM cards c
` + cardPrintingLateralJoin + `
WHERE c.set_id = $1
ORDER BY cp.set_num ASC, c.id ASC`
	rows, err := r.pool.Query(ctx, q, setID)
	if err != nil {
		return nil, fmt.Errorf("repository: cards by set id: %w", err)
	}
	defer rows.Close()

	out := make([]Card, 0, 64)
	for rows.Next() {
		c, err := scanCard(rows)
		if err != nil {
			return nil, fmt.Errorf("repository: cards by set id scan: %w", err)
		}
		out = append(out, *c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: cards by set id rows: %w", err)
	}
	return out, nil
}

// ListCards returns every card with set display name, ordered by set_code, set_num, id.
func (r *Repository) ListCards(ctx context.Context) ([]Card, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	q := `
SELECT ` + cardSelectColumnsFromC + `, s.name AS set_name
FROM cards c
` + cardPrintingLateralJoin + `
INNER JOIN sets s ON s.id = c.set_id
ORDER BY cp.set_code ASC, cp.set_num ASC, c.id ASC`
	rows, err := r.pool.Query(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("repository: list cards: %w", err)
	}
	defer rows.Close()

	out := make([]Card, 0, 256)
	for rows.Next() {
		c, err := scanCardWithSetName(rows)
		if err != nil {
			return nil, fmt.Errorf("repository: list cards scan: %w", err)
		}
		out = append(out, *c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: list cards rows: %w", err)
	}
	return out, nil
}
