package repository

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// ErrSetNotFound is returned when no row matches the requested set identifier.
var ErrSetNotFound = errors.New("repository: set not found")

// Set is a row from sets.
type Set struct {
	ID       int
	Name     string
	Code     string
	ImageURL *string
}

// CreateSetInput holds fields to insert a set (id is generated by the DB).
type CreateSetInput struct {
	Name     string
	Code     string
	ImageURL *string
}

// CreateSet inserts a set and returns the persisted row.
func (r *Repository) CreateSet(ctx context.Context, in CreateSetInput) (*Set, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
INSERT INTO sets (name, code, image_url)
VALUES ($1, $2, $3)
RETURNING id, name, code, image_url`
	row := r.pool.QueryRow(ctx, q, in.Name, in.Code, in.ImageURL)
	var s Set
	if err := row.Scan(&s.ID, &s.Name, &s.Code, &s.ImageURL); err != nil {
		return nil, fmt.Errorf("repository: create set: %w", err)
	}
	return &s, nil
}

// SetByID returns the set with the given id, or ErrSetNotFound.
func (r *Repository) SetByID(ctx context.Context, id int) (*Set, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
SELECT id, name, code, image_url
FROM sets
WHERE id = $1`
	row := r.pool.QueryRow(ctx, q, id)
	var s Set
	if err := row.Scan(&s.ID, &s.Name, &s.Code, &s.ImageURL); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrSetNotFound
		}
		return nil, fmt.Errorf("repository: set by id: %w", err)
	}
	return &s, nil
}

// SetByNameFold returns a set whose name matches case-insensitively after trim, or ErrSetNotFound.
func (r *Repository) SetByNameFold(ctx context.Context, name string) (*Set, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
SELECT id, name, code, image_url
FROM sets
WHERE lower(trim(name)) = lower(trim($1))
LIMIT 1`
	row := r.pool.QueryRow(ctx, q, name)
	var s Set
	if err := row.Scan(&s.ID, &s.Name, &s.Code, &s.ImageURL); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrSetNotFound
		}
		return nil, fmt.Errorf("repository: set by name fold: %w", err)
	}
	return &s, nil
}

// SetByCode returns the set with the given code, or ErrSetNotFound.
func (r *Repository) SetByCode(ctx context.Context, code string) (*Set, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
SELECT id, name, code, image_url
FROM sets
WHERE code = $1`
	row := r.pool.QueryRow(ctx, q, code)
	var s Set
	if err := row.Scan(&s.ID, &s.Name, &s.Code, &s.ImageURL); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrSetNotFound
		}
		return nil, fmt.Errorf("repository: set by code: %w", err)
	}
	return &s, nil
}

// ListSets returns all sets ordered by id ascending.
func (r *Repository) ListSets(ctx context.Context) ([]Set, error) {
	if r.pool == nil {
		return nil, fmt.Errorf("repository: pool is closed")
	}
	const q = `
SELECT id, name, code, image_url
FROM sets
ORDER BY id ASC`
	rows, err := r.pool.Query(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("repository: list sets: %w", err)
	}
	defer rows.Close()

	out := make([]Set, 0, 32)
	for rows.Next() {
		var s Set
		if err := rows.Scan(&s.ID, &s.Name, &s.Code, &s.ImageURL); err != nil {
			return nil, fmt.Errorf("repository: list sets scan: %w", err)
		}
		out = append(out, s)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository: list sets rows: %w", err)
	}
	return out, nil
}
